"""initial schema

Revision ID: 812721b2631a
Revises: 
Create Date: 2026-08-29 00:09:39.174779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812721b2631a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('full_name_en', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('direct_manager_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('pattern_hash', sa.String(length=255), nullable=True),
    sa.Column('allow_field_tracking', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['direct_manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.work_type_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index('idx_employee_manager', 'employees', ['direct_manager_id'], unique=False)
    op.create_index('idx_employee_org', 'employees', ['org_unit_id'], unique=False)
    op.create_index('idx_employee_work_type', 'employees', ['work_type_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_table('organization_units',
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('unit_name_en', sa.String(length=200), nullable=True),
    sa.Column('unit_code', sa.String(length=50), nullable=True),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('manager_employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('org_unit_id'),
    sa.UniqueConstraint('unit_code')
    )
    op.create_index('idx_org_unit_parent', 'organization_units', ['parent_id'], unique=False)
    op.create_index('idx_org_unit_type', 'organization_units', ['unit_type'], unique=False)
    op.create_index(op.f('ix_organization_units_org_unit_id'), 'organization_units', ['org_unit_id'], unique=False)
    op.create_index(op.f('ix_organization_units_parent_id'), 'organization_units', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_permission_code'), 'permissions', ['permission_code'], unique=True)
    op.create_index(op.f('ix_permissions_permission_id'), 'permissions', ['permission_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('work_scope_types',
    sa.Column('scope_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('type_name_ar', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('scope_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_work_scope_types_scope_type_id'), 'work_scope_types', ['scope_type_id'], unique=False)
    op.create_table('work_types',
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('type_name_ar', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_field', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('work_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_work_types_work_type_id'), 'work_types', ['work_type_id'], unique=False)
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_location', sa.Text(), nullable=True),
    sa.Column('check_out_location', sa.Text(), nullable=True),
    sa.Column('check_in_accuracy', sa.Float(), nullable=True),
    sa.Column('check_out_accuracy', sa.Float(), nullable=True),
    sa.Column('server_check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('identity_method', sa.String(length=50), nullable=True),
    sa.Column('is_mock_location', sa.Boolean(), nullable=False),
    sa.Column('device_uuid', sa.String(length=256), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('trust_status', sa.String(length=20), nullable=False),
    sa.Column('work_duration_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('overtime_status', sa.String(length=20), nullable=False),
    sa.Column('overtime_approved_by', sa.Integer(), nullable=True),
    sa.Column('overtime_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_mock_location_detected', sa.Boolean(), nullable=False),
    sa.Column('client_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index('idx_attendance_active', 'attendance', ['employee_id', 'status'], unique=False)
    op.create_index('idx_attendance_date', 'attendance', ['check_in_time'], unique=False)
    op.create_index('idx_attendance_employee', 'attendance', ['employee_id'], unique=False)
    op.create_index('idx_attendance_status', 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_attendance_id'), 'attendance', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_employee', 'audit_logs', ['employee_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('idx_audit_time', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_table('customer_service_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_cs_request_reporter', 'customer_service_requests', ['reported_by'], unique=False)
    op.create_index('idx_cs_request_status', 'customer_service_requests', ['status'], unique=False)
    op.create_index('idx_cs_request_type', 'customer_service_requests', ['service_type'], unique=False)
    op.create_index(op.f('ix_customer_service_requests_reported_by'), 'customer_service_requests', ['reported_by'], unique=False)
    op.create_index(op.f('ix_customer_service_requests_request_id'), 'customer_service_requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_customer_service_requests_request_number'), 'customer_service_requests', ['request_number'], unique=True)
    op.create_table('employee_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index('idx_assignment_active', 'employee_assignments', ['is_active'], unique=False)
    op.create_index('idx_assignment_employee', 'employee_assignments', ['employee_id'], unique=False)
    op.create_index('idx_assignment_org', 'employee_assignments', ['org_unit_id'], unique=False)
    op.create_index(op.f('ix_employee_assignments_assignment_id'), 'employee_assignments', ['assignment_id'], unique=False)
    op.create_table('employee_devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sa.String(length=256), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index('idx_device_employee', 'employee_devices', ['employee_id'], unique=False)
    op.create_index('idx_device_uuid', 'employee_devices', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_employee_devices_device_id'), 'employee_devices', ['device_id'], unique=False)
    op.create_table('field_tracking_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tracking_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_tracking_session_employee', 'field_tracking_sessions', ['employee_id'], unique=False)
    op.create_index('idx_tracking_session_status', 'field_tracking_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_field_tracking_sessions_employee_id'), 'field_tracking_sessions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_field_tracking_sessions_session_id'), 'field_tracking_sessions', ['session_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_leave_employee', 'leave_requests', ['employee_id'], unique=False)
    op.create_index('idx_leave_status', 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_request_id'), 'leave_requests', ['request_id'], unique=False)
    op.create_table('maintenance_complaints',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=50), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index('idx_maintenance_priority', 'maintenance_complaints', ['priority'], unique=False)
    op.create_index('idx_maintenance_reporter', 'maintenance_complaints', ['reported_by'], unique=False)
    op.create_index('idx_maintenance_status', 'maintenance_complaints', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_complaints_complaint_id'), 'maintenance_complaints', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_maintenance_complaints_complaint_number'), 'maintenance_complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_maintenance_complaints_reported_by'), 'maintenance_complaints', ['reported_by'], unique=False)
    op.create_table('meter_readings',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_number', sa.String(length=50), nullable=True),
    sa.Column('previous_reading', sa.Float(), nullable=False),
    sa.Column('current_reading', sa.Float(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('reading_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index('idx_meter_employee', 'meter_readings', ['employee_id'], unique=False)
    op.create_index('idx_meter_number', 'meter_readings', ['meter_number'], unique=False)
    op.create_index(op.f('ix_meter_readings_employee_id'), 'meter_readings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_meter_number'), 'meter_readings', ['meter_number'], unique=False)
    op.create_index(op.f('ix_meter_readings_reading_id'), 'meter_readings', ['reading_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notification_employee', 'notifications', ['employee_id'], unique=False)
    op.create_index('idx_notification_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_severity', 'notifications', ['severity'], unique=False)
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('scope_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index('idx_role_permission_perm', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_permission_role', 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_permission_id'), 'role_permissions', ['role_permission_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('device_uuid', sa.String(length=256), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('water_distribution_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=200), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('idx_wd_plan_date', 'water_distribution_plans', ['plan_date'], unique=False)
    op.create_index('idx_wd_plan_status', 'water_distribution_plans', ['status'], unique=False)
    op.create_index(op.f('ix_water_distribution_plans_plan_id'), 'water_distribution_plans', ['plan_id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index('idx_schedule_active', 'work_schedules', ['is_active'], unique=False)
    op.create_index('idx_schedule_employee', 'work_schedules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_schedules_employee_id'), 'work_schedules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_schedules_schedule_id'), 'work_schedules', ['schedule_id'], unique=False)
    op.create_table('work_scopes',
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('scope_type_id', sa.Integer(), nullable=False),
    sa.Column('scope_name', sa.String(length=200), nullable=False),
    sa.Column('scope_name_en', sa.String(length=200), nullable=True),
    sa.Column('parent_scope_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_scope_id'], ['work_scopes.scope_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_type_id'], ['work_scope_types.scope_type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scope_id')
    )
    op.create_index('idx_work_scope_active', 'work_scopes', ['is_active'], unique=False)
    op.create_index('idx_work_scope_employee', 'work_scopes', ['employee_id'], unique=False)
    op.create_index('idx_work_scope_type', 'work_scopes', ['scope_type_id'], unique=False)
    op.create_index(op.f('ix_work_scopes_employee_id'), 'work_scopes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_scopes_scope_id'), 'work_scopes', ['scope_id'], unique=False)
    op.create_table('customer_service_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['customer_service_requests.request_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_customer_service_events_event_id'), 'customer_service_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_customer_service_events_request_id'), 'customer_service_events', ['request_id'], unique=False)
    op.create_table('field_tracking_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['field_tracking_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index('idx_tracking_point_employee', 'field_tracking_points', ['employee_id'], unique=False)
    op.create_index('idx_tracking_point_session', 'field_tracking_points', ['session_id'], unique=False)
    op.create_index('idx_tracking_point_time', 'field_tracking_points', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_field_tracking_points_point_id'), 'field_tracking_points', ['point_id'], unique=False)
    op.create_index(op.f('ix_field_tracking_points_session_id'), 'field_tracking_points', ['session_id'], unique=False)
    op.create_table('maintenance_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance_complaints.complaint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_maintenance_assignments_assignment_id'), 'maintenance_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_assignments_complaint_id'), 'maintenance_assignments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_maintenance_assignments_worker_id'), 'maintenance_assignments', ['worker_id'], unique=False)
    op.create_table('overtime_work_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('area_lat', sa.Float(), nullable=False),
    sa.Column('area_lng', sa.Float(), nullable=False),
    sa.Column('area_radius_m', sa.Float(), nullable=False),
    sa.Column('requested_hours', sa.Float(), nullable=False),
    sa.Column('extended_hours', sa.Float(), nullable=False),
    sa.Column('total_approved_hours', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_session_id', sa.Integer(), nullable=True),
    sa.Column('tracking_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extended_by', sa.Integer(), nullable=True),
    sa.Column('extended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extended_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['tracking_session_id'], ['field_tracking_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_overtime_employee', 'overtime_work_requests', ['employee_id'], unique=False)
    op.create_index('idx_overtime_status', 'overtime_work_requests', ['status'], unique=False)
    op.create_index(op.f('ix_overtime_work_requests_employee_id'), 'overtime_work_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_overtime_work_requests_request_id'), 'overtime_work_requests', ['request_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_items', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.attendance_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance_complaints.complaint_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['organization_units.org_unit_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_report_employee', 'reports', ['employee_id'], unique=False)
    op.create_index('idx_report_status', 'reports', ['status'], unique=False)
    op.create_index('idx_report_type', 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_employee_id'), 'reports', ['employee_id'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('org_scope_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_scope_id'], ['organization_units.org_unit_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_index('idx_user_role_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_role_scope', 'user_roles', ['org_scope_id'], unique=False)
    op.create_index('idx_user_role_user', 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_role_id'), 'user_roles', ['user_role_id'], unique=False)
    op.create_table('water_distribution_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=200), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['water_distribution_plans.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index('idx_wd_assignment_distributor', 'water_distribution_assignments', ['distributor_id'], unique=False)
    op.create_index('idx_wd_assignment_status', 'water_distribution_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_water_distribution_assignments_assignment_id'), 'water_distribution_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_water_distribution_assignments_distributor_id'), 'water_distribution_assignments', ['distributor_id'], unique=False)
    op.create_index(op.f('ix_water_distribution_assignments_plan_id'), 'water_distribution_assignments', ['plan_id'], unique=False)
    op.create_table('maintenance_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['maintenance_assignments.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance_complaints.complaint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_maintenance_events_complaint_id'), 'maintenance_events', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_maintenance_events_event_id'), 'maintenance_events', ['event_id'], unique=False)
    op.create_table('overtime_work_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['overtime_work_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_overtime_work_reports_report_id'), 'overtime_work_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_overtime_work_reports_request_id'), 'overtime_work_reports', ['request_id'], unique=False)
    op.create_table('water_distribution_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['water_distribution_assignments.assignment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distributor_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_wd_event_assignment', 'water_distribution_events', ['assignment_id'], unique=False)
    op.create_index('idx_wd_event_type', 'water_distribution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_water_distribution_events_assignment_id'), 'water_distribution_events', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_water_distribution_events_event_id'), 'water_distribution_events', ['event_id'], unique=False)
    op.create_table('maintenance_photos',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['maintenance_complaints.complaint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['maintenance_events.event_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_maintenance_photos_complaint_id'), 'maintenance_photos', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_maintenance_photos_photo_id'), 'maintenance_photos', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_photos_photo_id'), table_name='maintenance_photos')
    op.drop_index(op.f('ix_maintenance_photos_complaint_id'), table_name='maintenance_photos')
    op.drop_table('maintenance_photos')
    op.drop_index(op.f('ix_water_distribution_events_event_id'), table_name='water_distribution_events')
    op.drop_index(op.f('ix_water_distribution_events_assignment_id'), table_name='water_distribution_events')
    op.drop_index('idx_wd_event_type', table_name='water_distribution_events')
    op.drop_index('idx_wd_event_assignment', table_name='water_distribution_events')
    op.drop_table('water_distribution_events')
    op.drop_index(op.f('ix_overtime_work_reports_request_id'), table_name='overtime_work_reports')
    op.drop_index(op.f('ix_overtime_work_reports_report_id'), table_name='overtime_work_reports')
    op.drop_table('overtime_work_reports')
    op.drop_index(op.f('ix_maintenance_events_event_id'), table_name='maintenance_events')
    op.drop_index(op.f('ix_maintenance_events_complaint_id'), table_name='maintenance_events')
    op.drop_table('maintenance_events')
    op.drop_index(op.f('ix_water_distribution_assignments_plan_id'), table_name='water_distribution_assignments')
    op.drop_index(op.f('ix_water_distribution_assignments_distributor_id'), table_name='water_distribution_assignments')
    op.drop_index(op.f('ix_water_distribution_assignments_assignment_id'), table_name='water_distribution_assignments')
    op.drop_index('idx_wd_assignment_status', table_name='water_distribution_assignments')
    op.drop_index('idx_wd_assignment_distributor', table_name='water_distribution_assignments')
    op.drop_table('water_distribution_assignments')
    op.drop_index(op.f('ix_user_roles_user_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index('idx_user_role_user', table_name='user_roles')
    op.drop_index('idx_user_role_scope', table_name='user_roles')
    op.drop_index('idx_user_role_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_employee_id'), table_name='reports')
    op.drop_index('idx_report_type', table_name='reports')
    op.drop_index('idx_report_status', table_name='reports')
    op.drop_index('idx_report_employee', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_overtime_work_requests_request_id'), table_name='overtime_work_requests')
    op.drop_index(op.f('ix_overtime_work_requests_employee_id'), table_name='overtime_work_requests')
    op.drop_index('idx_overtime_status', table_name='overtime_work_requests')
    op.drop_index('idx_overtime_employee', table_name='overtime_work_requests')
    op.drop_table('overtime_work_requests')
    op.drop_index(op.f('ix_maintenance_assignments_worker_id'), table_name='maintenance_assignments')
    op.drop_index(op.f('ix_maintenance_assignments_complaint_id'), table_name='maintenance_assignments')
    op.drop_index(op.f('ix_maintenance_assignments_assignment_id'), table_name='maintenance_assignments')
    op.drop_table('maintenance_assignments')
    op.drop_index(op.f('ix_field_tracking_points_session_id'), table_name='field_tracking_points')
    op.drop_index(op.f('ix_field_tracking_points_point_id'), table_name='field_tracking_points')
    op.drop_index('idx_tracking_point_time', table_name='field_tracking_points')
    op.drop_index('idx_tracking_point_session', table_name='field_tracking_points')
    op.drop_index('idx_tracking_point_employee', table_name='field_tracking_points')
    op.drop_table('field_tracking_points')
    op.drop_index(op.f('ix_customer_service_events_request_id'), table_name='customer_service_events')
    op.drop_index(op.f('ix_customer_service_events_event_id'), table_name='customer_service_events')
    op.drop_table('customer_service_events')
    op.drop_index(op.f('ix_work_scopes_scope_id'), table_name='work_scopes')
    op.drop_index(op.f('ix_work_scopes_employee_id'), table_name='work_scopes')
    op.drop_index('idx_work_scope_type', table_name='work_scopes')
    op.drop_index('idx_work_scope_employee', table_name='work_scopes')
    op.drop_index('idx_work_scope_active', table_name='work_scopes')
    op.drop_table('work_scopes')
    op.drop_index(op.f('ix_work_schedules_schedule_id'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_employee_id'), table_name='work_schedules')
    op.drop_index('idx_schedule_employee', table_name='work_schedules')
    op.drop_index('idx_schedule_active', table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_water_distribution_plans_plan_id'), table_name='water_distribution_plans')
    op.drop_index('idx_wd_plan_status', table_name='water_distribution_plans')
    op.drop_index('idx_wd_plan_date', table_name='water_distribution_plans')
    op.drop_table('water_distribution_plans')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index('idx_role_permission_role', table_name='role_permissions')
    op.drop_index('idx_role_permission_perm', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_index('idx_notification_severity', table_name='notifications')
    op.drop_index('idx_notification_read', table_name='notifications')
    op.drop_index('idx_notification_employee', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_meter_readings_reading_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_meter_number'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_employee_id'), table_name='meter_readings')
    op.drop_index('idx_meter_number', table_name='meter_readings')
    op.drop_index('idx_meter_employee', table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_maintenance_complaints_reported_by'), table_name='maintenance_complaints')
    op.drop_index(op.f('ix_maintenance_complaints_complaint_number'), table_name='maintenance_complaints')
    op.drop_index(op.f('ix_maintenance_complaints_complaint_id'), table_name='maintenance_complaints')
    op.drop_index('idx_maintenance_status', table_name='maintenance_complaints')
    op.drop_index('idx_maintenance_reporter', table_name='maintenance_complaints')
    op.drop_index('idx_maintenance_priority', table_name='maintenance_complaints')
    op.drop_table('maintenance_complaints')
    op.drop_index(op.f('ix_leave_requests_request_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index('idx_leave_status', table_name='leave_requests')
    op.drop_index('idx_leave_employee', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_field_tracking_sessions_session_id'), table_name='field_tracking_sessions')
    op.drop_index(op.f('ix_field_tracking_sessions_employee_id'), table_name='field_tracking_sessions')
    op.drop_index('idx_tracking_session_status', table_name='field_tracking_sessions')
    op.drop_index('idx_tracking_session_employee', table_name='field_tracking_sessions')
    op.drop_table('field_tracking_sessions')
    op.drop_index(op.f('ix_employee_devices_device_id'), table_name='employee_devices')
    op.drop_index('idx_device_uuid', table_name='employee_devices')
    op.drop_index('idx_device_employee', table_name='employee_devices')
    op.drop_table('employee_devices')
    op.drop_index(op.f('ix_employee_assignments_assignment_id'), table_name='employee_assignments')
    op.drop_index('idx_assignment_org', table_name='employee_assignments')
    op.drop_index('idx_assignment_employee', table_name='employee_assignments')
    op.drop_index('idx_assignment_active', table_name='employee_assignments')
    op.drop_table('employee_assignments')
    op.drop_index(op.f('ix_customer_service_requests_request_number'), table_name='customer_service_requests')
    op.drop_index(op.f('ix_customer_service_requests_request_id'), table_name='customer_service_requests')
    op.drop_index(op.f('ix_customer_service_requests_reported_by'), table_name='customer_service_requests')
    op.drop_index('idx_cs_request_type', table_name='customer_service_requests')
    op.drop_index('idx_cs_request_status', table_name='customer_service_requests')
    op.drop_index('idx_cs_request_reporter', table_name='customer_service_requests')
    op.drop_table('customer_service_requests')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_time', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_employee', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_id'), table_name='attendance')
    op.drop_index('idx_attendance_status', table_name='attendance')
    op.drop_index('idx_attendance_employee', table_name='attendance')
    op.drop_index('idx_attendance_date', table_name='attendance')
    op.drop_index('idx_attendance_active', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_work_types_work_type_id'), table_name='work_types')
    op.drop_table('work_types')
    op.drop_index(op.f('ix_work_scope_types_scope_type_id'), table_name='work_scope_types')
    op.drop_table('work_scope_types')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_permission_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_permission_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organization_units_parent_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_org_unit_id'), table_name='organization_units')
    op.drop_index('idx_org_unit_type', table_name='organization_units')
    op.drop_index('idx_org_unit_parent', table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index('idx_employee_work_type', table_name='employees')
    op.drop_index('idx_employee_org', table_name='employees')
    op.drop_index('idx_employee_manager', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
